query POCHEMU_RAMADA {
  pochemuRamadas {
    data {
        id
      attributes {
        H1
        H2
        Img {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
