query PRODUCT_ALL_CATALOG($PAGE: Int!) {
  products(pagination: { pageSize: $PAGE}) {
    meta {
      pagination {
        total
        page
        pageSize
        pageCount
      }
    }
    data {
      id
      attributes {
        Name
        Art
        Price
        SalePrice
        Desc
        UID
        Model
        Active
        Characteristic {
          Proizvidotel
          Razmer
        }
        Img {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
