query PRODUCT_CAT($PAGE: Int! , $URL: String) {
  products(
    pagination: { pageSize: $PAGE},
    filters: {
      categories: {
        URL : {
          eq: $URL
        }
      }
    }
  ) {
    meta {
      pagination {
        total
        page
        pageSize
        pageCount
      }
    }
    data {
      id
      attributes {
        Name
        Art
        Price
        SalePrice
        Desc
        UID
        Model
        Active
        categories{
          data{
            attributes{
              Name
            }
          }
        }
        Characteristic {
          Proizvidotel
          Razmer
        }
        Img {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
