query PRODUCT_ID($ID: ID) {
  product(id: $ID) {
    data {
      id
      attributes {
        Name
        Art
        Price
        SalePrice
        Desc
        UID
        Model
        Active
        Characteristic {
          id
          Proizvidotel
          Razmer
        }
        ColorDerevo {
          id
          Name
          Price
        }
        ColorMetal {
          id
          Name
          Price
        }
        Specifics {
          id
          Name
          Value
        }
        Img {
          data {
            attributes {
              url
            }
          }
        }
        up_sales {
          data {
            id
            attributes {
              Name
              Art
              Price
              SalePrice
              Desc
              UID
              Model
              Characteristic {
                Proizvidotel
                Razmer
              }
              Img {
                data {
                  attributes {
                    url
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
